apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stage-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: stage-proxy
    spec:
      containers:
        - image: nginx
          name: stage-proxy-web
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - name: "nginx-proxy-conf"
              mountPath: "/etc/nginx/conf.d"
          ports:
            - containerPort: 6060
              name: stage-proxy-tcp
        - image: andyshinn/dnsmasq:2.78
          name: stage-proxy-dns
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          ports:
            - containerPort: 53
              name: stage-proxy-dns
      volumes:
        - name: nginx-proxy-conf
          configMap:
            name: stage-proxy-config
            items:
              - key: "nginx.conf"
                path: "nginx.conf"
