apiVersion: v1
kind: Service
metadata:
  name: stage-proxy
  labels:
    run: stage-proxy
spec:
  type: NodePort
  ports:
  - port: 6060
    targetPort: 6060
    nodePort: 30606
    protocol: TCP
    name: stage-proxy-http
  selector:
    service: stage-proxy
