apiVersion: v1
data:
  nginx.conf: "  set_real_ip_from 0.0.0.0/0;\n  real_ip_header X-Forwarded-For;\n
    \ real_ip_recursive on;\n\n  log_format h_upstream '$remote_addr - $remote_user
    [$time_local] '\n                        '\"$request\" $status $body_bytes_sent
    '\n                        '\"$http_referer\" \"$http_user_agent\" \"$host\"'\n
    \                       'rt=$request_time uct=\"$upstream_connect_time\" uht=\"$upstream_header_time\"
    urt=\"$upstream_response_time\"';\n\n  server {\n    listen 6060;\n    access_log
    /var/log/nginx/access.log h_upstream;\n\n    server_name staging.api.sense.tw;\n
    \   server_tokens off;\n\n    root /var/www;\n\n    location /health {\n        access_log
    off;\n        return 200;\n    }\n\n    location / {\n      resolver 127.0.0.1;\n
    \     if ($http_x_forwarded_proto != \"https\") {\n          rewrite ^(.*)$ https://$host$1
    permanent;\n      }\n      \n      set $target http://api-master.default.svc.cluster.local:8000;\n
    \     proxy_pass http://api-master.default.svc.cluster.local:8000;\n      proxy_http_version
    1.1;\n      proxy_connect_timeout 10s;\n      proxy_send_timeout 10s;\n      proxy_read_timeout
    10s;\n      proxy_redirect off;\n      proxy_set_header Host $host;\n      proxy_set_header
    X-Forwarded-Server $http_host;\n      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n
    \     proxy_set_header X-Request-Start \"t=${msec}\";\n    }\n  }\n\n  server
    {\n    listen 6060;\n    access_log /var/log/nginx/access.log h_upstream;\n\n
    \   server_name ~^(?<subdomain>\\w+)\\.staging\\.api\\.sense\\.tw$;\n    server_tokens
    off;\n\n    root /var/www;\n\n    location /health {\n        access_log off;\n
    \       return 200;\n    }\n\n    location / {\n      resolver 127.0.0.1;\n      if
    ($http_x_forwarded_proto != \"https\") {\n          rewrite ^(.*)$ https://$host$1
    permanent;\n      }\n\n      proxy_pass http://api-$subdomain.default.svc.cluster.local:8000;\n
    \     proxy_http_version 1.1;\n      proxy_connect_timeout 10s;\n      proxy_send_timeout
    10s;\n      proxy_read_timeout 10s;\n      proxy_redirect off;\n      proxy_set_header
    Host $host;\n      proxy_set_header X-Forwarded-Server $http_host;\n      proxy_set_header
    X-Forwarded-For $proxy_add_x_forwarded_for;\n      proxy_set_header X-Request-Start
    \"t=${msec}\";\n    }\n  }\n\n  server {\n    listen 6060;\n    server_name _;\n\n
    \   location /health {\n        access_log off;\n        return 200;\n    }\n
    \ }\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: stage-proxy-config
