apiVersion: v1
kind: ConfigMap
metadata:
  name: db-restore-sensemap-${BRANCH_NAME}-env
  namespace: default
data:
  PGDATABASE: ${DB_NAME}
  PGHOST: ${DB_HOST}
  PGPORT: "5432"
  PGUSER: ${DB_ACCOUNT}
  PGPASSWORD: ${DB_PASSWORD}
  GS_BUCKET_PATH: gs://${GS_BACKUP_BUCKET}
  GCLOUD_CREDENTIALS: /secrets/gcloud/credentials.json
