apiVersion: v1
kind: Service
metadata:
  name: sensemap-${BRANCH_NAME}
  labels:
    run: sensemap-${BRANCH_NAME}
spec:
  type: NodePort
  ports:
  - port: 6000
    targetPort: 6000
    nodePort: 30600
    protocol: TCP
    name: sensemap-${BRANCH_NAME}-http
  selector:
    service: sensemap-${BRANCH_NAME}
