apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensemap-${BRANCH_NAME}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: sensemap-${BRANCH_NAME}
    spec:
      containers:
        - image: asia.gcr.io/ggv-notetool/db-backup:latest
          imagePullPolicy: Always
          name: restore-worker
          args:
            - restore
            - sensemap
            - keep-alive
          envFrom:
            - configMapRef:
                name: db-restore-sensemap-${BRANCH_NAME}-env
          volumeMounts:
            - name: gcloud-credentials
              mountPath: /secrets/gcloud
              readOnly: true
            - mountPath: /tmp/pod
              name: tmp-pod
          resources:
            requests:
              memory: "8Mi"
              cpu: "1m"
        - image: nginx:1.15-alpine-perl
          name: sensemap-web
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          envFrom:
            - configMapRef:
                name: sensemap-${BRANCH_NAME}-web-env
          volumeMounts:
            - name: "nginx-proxy-site-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "nginx-proxy-conf"
              mountPath: "/etc/nginx/nginx.conf"
              subPath: "nginx.conf"
            - name: "nginx-proxy-conf"
              mountPath: "/etc/nginx/module.conf"
              subPath: "module.conf"
            - name: front-static
              mountPath: /var/front
          ports:
            - containerPort: 6000
              name: sensemap-tcp
        - image: gcr.io/ggv-notetool/sensemap:${COMMIT_SHA}
          imagePullPolicy: Always
          name: sensemap
          args: ["cloudbuild-staging"]
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /static/* /shared-static/"]
          ports:
          - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
          envFrom:
            - configMapRef:
                name: sensemap-${BRANCH_NAME}-env
          volumeMounts:
            - name: front-static
              mountPath: /shared-static
            - name: tmp-pod
              mountPath: /tmp/pod
        - image: gcr.io/ggv-notetool/sensemap-smo:${COMMIT_SHA}
          imagePullPolicy: Always
          name: sensemap-smo
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
          envFrom:
            - configMapRef:
                name: sensemap-smo-${BRANCH_NAME}-env
      volumes:
        - name: nginx-proxy-site-conf
          configMap:
            name: sensemap-${BRANCH_NAME}-web-config
            items:
              - key: "default.conf"
                path: "default.conf"
        - name: nginx-proxy-conf
          configMap:
            name: sensemap-${BRANCH_NAME}-web-config
            items:
              - key: "nginx.conf"
                path: "nginx.conf"
              - key: "module.conf"
                path: "module.conf"
        - name: gcloud-credentials
          secret:
            secretName: db-backup-credentials
        - name: sensemap-${BRANCH_NAME}-web-env
          configMap:
            name: sensemap-${BRANCH_NAME}-web-env
        - name: sensemap-${BRANCH_NAME}-env
          configMap:
            name: sensemap-${BRANCH_NAME}-env
        - name: sensemap-smo-${BRANCH_NAME}-env
          configMap:
            name: sensemap-smo-${BRANCH_NAME}-env
        - name: front-static
          emptyDir:
        - name: db-restore-sensemap-${BRANCH_NAME}-env
          configMap:
            name: db-restore-sensemap-${BRANCH_NAME}-env
        - name: tmp-pod
          emptyDir:

