apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensemap-${BRANCH_NAME}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: sensemap-${BRANCH_NAME}
    spec:
      containers:
        - image: nginx
          name: sensemap-web
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - name: "nginx-proxy-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: front-static
              mountPath: /var/front
          ports:
            - containerPort: 6000
              name: sensemap-tcp
        - image: gcr.io/ggv-notetool/sensemap:${COMMIT_SHA}
          imagePullPolicy: Always
          name: sensemap
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /static/* /shared-static/"]
          ports:
          - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: sensemap-${BRANCH_NAME}-env
          volumeMounts:
            - name: front-static
              mountPath: /shared-static
      volumes:
        - name: nginx-proxy-conf
          configMap:
            name: sensemap-${BRANCH_NAME}-web-config
            items:
              - key: "nginx.conf"
                path: "nginx.conf"
        - name: sensemap-${BRANCH_NAME}-env
          configMap:
            name: sensemap-${BRANCH_NAME}-env
        - name: front-static
          emptyDir:
