steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/sensemap-backend',
         '-t', 'gcr.io/$PROJECT_ID/sensemap-backend:$COMMIT_SHA',
         '-f', './sensemap-backend/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/sensemap-backend"]

- name: gcr.io/cloud-builders/docker
  args: ['run', '-v', '/workspace/sensemap:/workspace', 'gcr.io/$PROJECT_ID/sense-builder', "release", '$COMMIT_SHA']
- name: gcr.io/cloud-builders/gsutil
  args: ['-h', 'Cache-Control:private', 'cp', '-r','-a', 'public-read', '/workspace/sensemap/gcs-build/*', 'gs://sensetw/$COMMIT_SHA/']
- name: gcr.io/cloud-builders/gsutil
  args: ['-h', 'Cache-Control:private', 'cp', '-r', '-a', 'public-read', '/workspace/sensemap/gcs-build/*', 'gs://sensetw/']
