steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/sensemap-backend',
         '-t', 'gcr.io/$PROJECT_ID/sensemap-backend:$COMMIT_SHA',
         '-f', './sensemap-backend/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/sensemap-backend"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/sensemap-backend'
  - 'sensemap-backend=gcr.io/$PROJECT_ID/sensemap-backend:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
